name: Deploy Blog to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库源码
        uses: actions/checkout@v4
      - name: 配置Node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: 安装VitePress依赖
        run: npm install
      - name: 打包静态博客页面
        run: npm run build
      - name: 上传打包产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist
      - name: 部署到GitHub Pages
        uses: actions/deploy-pages@v4
